name: publish
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install all necessary packages
      run: pip install jupyter lxml pandas requests beautifulsoup4
    - name: Run the scraping script
      run: jupyter nbconvert --to notebook --execute "quake_and_aftershocks.ipynb" --stdout
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
